---
- hosts: "{{ passed_in_hosts }}"
  become: yes
  remote_user: ec2-user
  become_user: root
  gather_facts: no
  tasks:
    - name: install jq, JSON parser
      yum:
        name: jq
        state: present
